### ISSUE TITLE
Find a bug

### ISSUE THREAD

**Issue by hxdyj** [willhoag/angle-between-points#1]
This is right
`angleBetweenPoints( {x: 2, y: 0}, {x: -4, y: 0} );
// returns 180 
`

This is Bug
`angleBetweenPoints( {x: -2, y: 0}, {x: 4, y: 0} );
// returns 0
`

**Comment by willhoag** [comment]
Hy @hxdyj, can you elaborate how it's a bug?

A line from -X to +X only (with no change in Y) would have an angle of 0 degrees.

**Comment by hxdyj** [comment]
I think {x: -2, y: 0}, {x: 4, y: 0} two point angle should be 180 degree

**Comment by willhoag** [comment]
Think of the 1st point as the start of the line and the 2nd as the end.

So, if the line is flat and goes to the right, it's 0 degrees (or 360 degrees), and if it's flat and goes to the left, it's 180 degrees.

![angle](https://user-images.githubusercontent.com/982131/34222598-56b8d398-e579-11e7-8ac7-7fa0bf919107.png)
![ucad](https://user-images.githubusercontent.com/982131/34222600-5a5bb5ce-e579-11e7-86f3-50bbf739e1a3.gif)

**Comment by hxdyj** [comment]
I understand you mean. Thank you.

**Comment by willhoag** [comment]
Your welcome. Thank you. 👍
